[CustomConnecto] Add new interfaces to support create
microsoft/PowerApps-Samples pull request #487
Opened 2023-10-09 22:17 UTC by xxhice

2023-10-09 22:19 UTC, abithap commented on model-driven-apps/custom-connectors/SecondaryRecordSource/solution/Interfaces.d.ts
> +	}
nit: formatting

2023-10-09 22:20 UTC, abithap approved these changes

2023-10-10 00:03 UTC, JimDaly requested changes
Let's not use the word 'deprecated' to refer to the older solution file.
Please explain why you still want to keep it around.
Or get rid of it with confidence that the newer improved version will work for people.
Otherwise, no one will know why it is there.

2023-10-10 17:56 UTC, abithap approved these changes

2023-10-10 17:58 UTC, JimDaly approved these changes

2023-10-10 17:58 UTC, merged